
project_id = "ceynoheuiwfkxizveshp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ceynoheuiwfkxizveshp.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.analyze-sentiment]
verify_jwt = false
