// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceynoheuiwfkxizveshp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNleW5vaGV1aXdma3hpenZlc2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjQzNTUsImV4cCI6MjA2NTA0MDM1NX0.lxLSRz95t9L4oPpcIP383AJiBij1lRjd5ffbNj0g6QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);